# Generated by Django 5.0.4 on 2024-05-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisName',
            fields=[
                ('Analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('promo_code', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('examination_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_examination', models.TextField()),
                ('examination_date', models.DateField()),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.addassistantstaff')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.addnewmedicalstaff')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisX_ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analysis', models.ManyToManyField(related_name='analysis', to='patient.analysisname')),
                ('examination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.examination')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_examination', models.TextField()),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.examination')),
                ('medicine', models.ManyToManyField(blank=True, related_name='posts_liked', to='patient.medicinename')),
            ],
        ),
        migrations.CreateModel(
            name='QueueExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('activate', models.BooleanField(default=False)),
                ('examination_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.examination')),
            ],
        ),
        migrations.CreateModel(
            name='TypeExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('temperature', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('hear_beat', models.PositiveIntegerField()),
                ('hypertension', models.PositiveIntegerField()),
                ('low_blood_pressure', models.PositiveIntegerField()),
                ('head_circumference', models.PositiveIntegerField()),
                ('medical_diagnosis', models.TextField()),
                ('reexamination_date', models.DateField(null=True)),
                ('examination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.examination')),
            ],
        ),
    ]
