# Generated by Django 5.0.4 on 2024-05-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisx_ray',
            name='analysis',
            field=models.ManyToManyField(blank=True, related_name='analysis', to='patient.analysisname'),
        ),
    ]
