# Generated by Django 5.0.4 on 2024-05-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_analysisx_ray_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisx_ray',
            name='analysis',
            field=models.ManyToManyField(related_name='analysis', to='patient.analysisname'),
        ),
    ]
