# Generated by Django 5.0.4 on 2024-05-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_typeexamination_examination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeexamination',
            name='examination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.examination'),
        ),
    ]
