# Generated by Django 5.0.4 on 2024-05-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_typeexamination_examination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexamination',
            name='examination_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.examination'),
        ),
        migrations.AlterField(
            model_name='analysisx_ray',
            name='examination_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.examination'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='examination_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.examination'),
        ),
    ]
